# method: bayes
method: grid
name: test_msae_allen_732592105
metric:
  name: loss
  goal: minimize
wandb_config:
  entity: jkbhagatio
  project: MINI
sweep_config:
  n_runs: 72
# slurm_config:
#   slurm_job_name: SANe_allen_732592105_sweep
#   log_dir: /nfs/nhome/live/jbhagat/mini/slurm_logs
#   slurm_partition: gpu_branco
#   nodelist: gpu-sr675-32
#   n_tasks: 4
#   gpus_per_task: 1
#   cpus_per_task: 16
#   mem_gb: 128
parameters:
  dsae_topk_level_map: 
    values: [
      {1024: 12, 2048: 24, 4096: 48}, 
      {2048: 16, 4096: 32, 8192: 48}
    ]
  lr:
    values: [5e-3]
  loss_fn:
    values: [msle_1.0]
  n_instances:
    values: [2]
  seq_len:
    values: [1]
  batch_size:
    values: [1024]
  epochs:
    values: [30]
  use_lr_sched:
    values: [true]
# early_terminate:
#   type: hyperband
#   s: 0
#   min_iter: 34
#   eta: 3
