# method: bayes
method: grid
name: test_SANe_allen_760693773_dsae_topk
metric:
  name: loss
  goal: minimize
wandb_config:
  entity: jkbhagatio
  project: MINI
sweep_config:
  n_runs: 72
# slurm_config:
#   slurm_job_name: SANe_allen_732592105_sweep
#   log_dir: /nfs/nhome/live/jbhagat/mini/slurm_logs
#   slurm_partition: gpu_branco
#   nodelist: gpu-sr675-32
#   n_tasks: 4
#   gpus_per_task: 1
#   cpus_per_task: 16
#   mem_gb: 128
parameters:
  d_sae:
    # values: [4096, 8192, 16384, 32768, 65536]
    values: [1024, 2048, 4096]
  top_k:
    # values: [16, 24, 32, 48, 64, 96, 128]
    values: [12, 24, 48]
  # lr:
  #   min: 5.0e-4
  #   max: 1.0e-2
  #   distribution: log_uniform_values
  lr:
    values: [5e-3]
    # values: [5e-4, 1e-3, 5e-3, 1e-2]
    # values: [1e-4, 8e-4, 1.5e-3, 2.2e-3, 2.9e-3, 3.6e-3, 4.3e-3, 5e-3]  # linspaced
    # values: [1e-4, 1.8e-4, 3.1e-4, 5.3e-4, 9.4e-4, 1.6e-3, 2.9e-3, 5e-3]  # logspaced
  loss_fn:
    # values: [msle_0.9, msle_1.0, msle_1.1]
    values: [msle_1.0]
  n_instances:
    values: [2]
  seq_len:
    values: [1]
  batch_size:
    values: [1024]
  epochs:
    values: [30]
  use_lr_sched:
    values: [true]
# early_terminate:
#   type: hyperband
#   s: 0
#   min_iter: 34
#   eta: 3
